contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #myfirstpipeline channel"
    url: https://nfcore.slack.com/channels/myfirstpipeline
    about: Discussion about the nf-core/myfirstpipeline pipeline
